# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x1b\n\x0eProdCatRequest\x12\t\n\x01\x63\x18\x01 \x01(\x05\"\x1b\n\x0cProdCatReply\x12\x0b\n\x03\x63\x61t\x18\x01 \x03(\t\"\x1f\n\x0bProdRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\xa5\x01\n\tProdReply\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12-\n\nprod_price\x18\x02 \x03(\x0b\x32\x19.ProdReply.ProdPriceEntry\x1a\x13\n\x05Price\x12\n\n\x02pr\x18\x01 \x01(\x02\x1a\x42\n\x0eProdPriceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.ProdReply.Price:\x02\x38\x01\x32W\n\x04Shop\x12*\n\x08GetCateg\x12\x0f.ProdCatRequest\x1a\r.ProdCatReply\x12#\n\x07GetProd\x12\x0c.ProdRequest\x1a\n.ProdReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _PRODREPLY_PRODPRICEENTRY._options = None
  _PRODREPLY_PRODPRICEENTRY._serialized_options = b'8\001'
  _globals['_PRODCATREQUEST']._serialized_start=18
  _globals['_PRODCATREQUEST']._serialized_end=45
  _globals['_PRODCATREPLY']._serialized_start=47
  _globals['_PRODCATREPLY']._serialized_end=74
  _globals['_PRODREQUEST']._serialized_start=76
  _globals['_PRODREQUEST']._serialized_end=107
  _globals['_PRODREPLY']._serialized_start=110
  _globals['_PRODREPLY']._serialized_end=275
  _globals['_PRODREPLY_PRICE']._serialized_start=188
  _globals['_PRODREPLY_PRICE']._serialized_end=207
  _globals['_PRODREPLY_PRODPRICEENTRY']._serialized_start=209
  _globals['_PRODREPLY_PRODPRICEENTRY']._serialized_end=275
  _globals['_SHOP']._serialized_start=277
  _globals['_SHOP']._serialized_end=364
# @@protoc_insertion_point(module_scope)
