# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class ShopStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCateg = channel.unary_unary(
                '/Shop/GetCateg',
                request_serializer=messages__pb2.ProdCatRequest.SerializeToString,
                response_deserializer=messages__pb2.ProdCatReply.FromString,
                )
        self.GetProd = channel.unary_unary(
                '/Shop/GetProd',
                request_serializer=messages__pb2.ProdRequest.SerializeToString,
                response_deserializer=messages__pb2.ProdReply.FromString,
                )


class ShopServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCateg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCateg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCateg,
                    request_deserializer=messages__pb2.ProdCatRequest.FromString,
                    response_serializer=messages__pb2.ProdCatReply.SerializeToString,
            ),
            'GetProd': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProd,
                    request_deserializer=messages__pb2.ProdRequest.FromString,
                    response_serializer=messages__pb2.ProdReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Shop', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shop(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCateg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Shop/GetCateg',
            messages__pb2.ProdCatRequest.SerializeToString,
            messages__pb2.ProdCatReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Shop/GetProd',
            messages__pb2.ProdRequest.SerializeToString,
            messages__pb2.ProdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
